DEBUG		 = YES

PROG		 = power_v1
SRCS		 = main.cpp \
		   slave.cpp

SRCS		+= board.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   param_power_v1.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp \
		   util.cpp

BOARD		 = POWER_V1

include ../rules.mk
