DEBUG		 = YES

PROG		 = PowerV1
SRCS		 = main.cpp \
		   slave.cpp

SRCS		+= lin_defs.cpp

SRCS		+= board.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp \
		   util.cpp

BOARD		 = POWER_V1

build: bin

include ../rules.mk
