DEBUG		 = YES

PROG		 = programmer
SRCS		 = main.cpp \
		   encoder.cpp \
		   hd44780.cpp \
		   menu.cpp \
		   m_edit.cpp \
		   m_top.cpp \
		   m_explore.cpp \
		   m_setup.cpp \
		   m_test.cpp

SRCS		+= board.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp

BOARD		 = PROGRAMMER_V1

include ../rules.mk
