DEBUG		 = YES

PROG		 = programmer
SRCS		 = main.cpp \
		   hd44780.cpp \

SRCS		+= board.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp

BOARD		 = PROGRAMMER_V1

include ../rules.mk
