DEBUG		 = YES

PROG		 = relays
SRCS		 = main.cpp \
		   slave.cpp

SRCS		+= board.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp

BOARD		 = POWER_V1

include ../rules.mk
