DEBUG		 = YES

PROG		 = master
SRCS		 = main.cpp \
		   display.cpp \
		   master.cpp \
		   menu.cpp \
		   slave.cpp \
		   switches.cpp

SRCS		+= board.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp \
		   USI_TWI_Master.c

BOARD		 = NODE_V1
#FUSES		 = $(RES_FUSES)

include ../rules.mk
