
PROG		 = master
SRCS		 = main.cpp \
		   display.cpp \
		   master.cpp \
		   board.cpp \
		   lin_drv.c \
		   lin_slave.cpp \
		   timer.cpp \
		   USI_TWI_Master.c

BOARD		 = NODE_V1

include ../rules.mk
