DEBUG		 = YES

PROG		 = programmer
SRCS		 = main.cpp \
		   menu.cpp \
		   m_edit.cpp \
		   m_top.cpp \
		   m_explore.cpp \
		   m_info.cpp \
		   m_setup.cpp \
		   m_test.cpp \
		   slave.cpp

SRCS		+= lin_defs.cpp

SRCS		+= board.cpp \
		   encoder.cpp \
		   hd44780.cpp \
		   lin_dev.cpp \
		   lin_slave.cpp \
		   print.cpp \
		   softserial.cpp \
		   timer.cpp \
		   util.cpp

BOARD		 = PROGRAMMER_V1

include ../rules.mk
